title: Page
pages: true
files: true
fields:
  tab1:
    label: Header Section
    type:  tabs
  title:
    label: Title
    type:  text
  text:
    label: Text
    type:  textarea
  tab2:
    label: About Section
    type:  tabs
  abouttitle:
    label: Title
    type:  text
  abouttext:
    label: Text
    type:  textarea
  tab3:
    label: Services Section
    type:  tabs
  servicetitle:
    label: Title
    type:  text
  servicetext:
    label: Text
    type:  textarea
  tab4:
    label: Contact Section
    type:  tabs
  contacttitle:
    label: Title
    type:  text
  contacttext:
    label: Text
    type:  textarea
