title: Site
pages: true
files: true
fields:
  title:
    label: Title
    type:  text
  description:
    label: Description
    type:  textarea
  keywords:
    label: Keywords
    type:  tags  
  copyright:
    label: Copyright
    type:  textarea    